curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Смартфон Samsung Galaxy S23" -F "description=Флагманский смартфон с AMOLED экраном 6.1 дюйма" -F "imageFile=@example/item1.jpg" -F "price=79999.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Ноутбук Apple MacBook Air M2" -F "description=Легкий ноутбук с процессором Apple M2 и дисплеем Retina" -F "imageFile=@example/item2.jpg" -F "price=109999.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Наушники Sony WH-1000XM5" -F "description=Беспроводные наушники с шумоподавлением" -F "imageFile=@example/item3.jpg" -F "price=29990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Телевизор LG OLED C3" -F "description=55-дюймовый OLED телевизор с разрешением 4K" -F "imageFile=@example/item4.jpg" -F "price=89990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Фотоаппарат Canon EOS R6 Mark II" -F "description=Беззеркальная камера с полнокадровым сенсором" -F "imageFile=@example/item5.jpg" -F "price=179990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Умные часы Apple Watch Series 9" -F "description=Смарт-часы с функцией измерения ЭКГ" -F "imageFile=@example/item6.jpg" -F "price=39990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Игровая консоль PlayStation 5" -F "description=Игровая приставка с SSD накопителем" -F "imageFile=@example/item7.jpg" -F "price=59990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Клавиатура Logitech MX Keys" -F "description=Беспроводная клавиатура с подсветкой" -F "imageFile=@example/item8.jpg" -F "price=8990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Мышь Razer DeathAdder V3" -F "description=Игровая мышь с оптическим сенсором" -F "imageFile=@example/item9.jpg" -F "price=7990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Колонка JBL Charge 5" -F "description=Портативная Bluetooth колонка с влагозащитой" -F "imageFile=@example/item10.jpg" -F "price=12990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Электронная книга PocketBook 740" -F "description=7.8-дюймовая читалка с защитой от воды" -F "imageFile=@example/item11.jpg" -F "price=24990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Робот-пылесос Xiaomi Robot Vacuum S10" -F "description=Робот-пылесос с лазерной навигацией" -F "imageFile=@example/item12.jpg" -F "price=29990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Монитор Dell UltraSharp U2723QE" -F "description=27-дюймовый 4K монитор с матрицей IPS" -F "imageFile=@example/item13.jpg" -F "price=65990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Внешний SSD Samsung T7 1TB" -F "description=Портативный SSD накопитель с USB 3.2" -F "imageFile=@example/item14.jpg" -F "price=8990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Принтер HP LaserJet Pro M-FP M141w" -F "description=Лазерный МФУ с Wi--Fi" -F "imageFile=@example/item15.jpg" -F "price=14990.00" localhost:8081/admin/items/add
curl -i -X POST -H "Content-Type: multipart/form-data" -F "title=Велосипед BMC Speedmachine" -F "description=Шоссейный велосипед BMC Speedmachine 01 ONE Red AXS (2024), S, белый" -F "imageFile=@example/item16.jpg" -F "price=999999.00" localhost:8081/admin/items/add
